/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_konote_opencv_03_MainActivity */

#ifndef _Included_com_example_konote_opencv_03_MainActivity
#define _Included_com_example_konote_opencv_03_MainActivity
#ifdef __cplusplus

extern "C" {

#endif
#undef com_example_konote_opencv_03_MainActivity_PERMISSIONS_REQUEST_CODE
#define com_example_konote_opencv_03_MainActivity_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_example_konote_opencv_03_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
//JNIEXPORT void JNICALL Java_com_example_konote_opencv_103_MainActivity_ConvertRGBtoGray
//  (JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong JNICALL
Java_com_example_konote_opencv_103_MainActivity_loadCascade(JNIEnv *env, jclass type, jstring cascadeFileName_);


JNIEXPORT jint JNICALL
Java_com_example_konote_opencv_103_MainActivity_detect(JNIEnv *env, jclass type, jlong cascadeClassifier_face, jlong cascadeClassifier_eye, jlong matAddrInput, jlong matAddrResult);

#ifdef __cplusplus
}

#endif
#endif
