/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_konote_weetalk_OpenCVActivity */

#ifndef _Included_com_example_konote_weetalk_OpenCVActivity
#define _Included_com_example_konote_weetalk_OpenCVActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_konote_weetalk_OpenCVActivity_PERMISSIONS_REQUEST_CODE
#define com_example_konote_weetalk_OpenCVActivity_PERMISSIONS_REQUEST_CODE 1000L


JNIEXPORT jlong JNICALL
Java_com_example_konote_weetalk_OpenCVActivity_loadCascade(JNIEnv *env, jclass type, jstring cascadeFileName_);


JNIEXPORT jint JNICALL
Java_com_example_konote_weetalk_OpenCVActivity_detect(JNIEnv *env, jclass type, jlong cascadeClassifier_face, jlong cascadeClassifier_eye, jlong matAddrInput, jlong matAddrResult);





#ifdef __cplusplus
}
#endif
#endif
